config/routes.rb
Rails.application.routes.draw do
  get 'goods/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :goods do
    member  do
      get 'stock'
      get 'filling_report'
      patch 'filling_report_func'
    end
  end
  
  get '/product_reports', to: 'goods#product_report'
  resources :items do
    member do
      get 'edit_material_info'
      patch 'update_material_info'
    end
    resources :products do
      member do
        get 'production_new'
        patch 'production_create'
      end
    end
  end
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :item
  has_many :goods_material
  
  validates :client_name, presence: true
  validates :goods_name, presence: true
  validates :quantity, presence: true
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_goods, only: [:edit, :update, :stock, :filling_report]
  before_action :logged_in_user, only: [:show, :edit, :update, :index, :destroy]
  
  def index
    @goods = Good.all
  end 
  
  def new
    @good = Good.new
  end
  
  def create
    @good = Good.new(goods_params)
    if @good.save
      flash[:success] = "製品を登録しました。"
      redirect_to goods_path
    else
      render :new
    end
  end 
  
  def destroy
    @good = Good.find(params[:id])
    @good.destroy
    flash[:success] = "#{@good.client_name}・#{@good.goods_name}・#{@good.quantity}を削除しました。"
    redirect_to goods_url
  end
  
  def stock
  end
  
  def product_report
    @goods = Good.all
  end
  
  def filling_report
  end
  
  def filling_report_func
  end
  

  
  private
  
  def goods_params
    params.require(:good).permit(:client_name, :goods_name, :quantity)
  end
  
  def set_goods
    @good = Good.find(params[:id])
  end
  
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_edit.html.erb
<% provide(:class_text, "goods--edit") %>
<% provide(:button_text, "登録") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">製品情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @good, local: true) do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
            
            <%= f.label :client_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :client_name, class: "form-control" %>
            
            <%= f.label :goods_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :goods_name, class: "form-control" %>
            
            <%= f.label :quantity, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :quantity, class: "form-control new_quantity_field", step: 5 %>
            
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goods/_filling_report.html.erb
<% provide(:class_text, "filling-report") %>
<% provide(:button_text, "送信") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">
        <%= @good.client_name %>  <%= @good.goods_name %> <%= @good.quantity %>包　充填生産報告
      </h1>
    </div>
    <div class="modal-body">
      <div class="col-md-10 col-md-offset-1">
        <%= form_with(model: @good, local: true) do |f| %>
        
          <%= f.label :product_day, class: "label-class" %>
          <%= f.date_field :product_day, value: Time.now.strftime("%Y-%m-%d"), class: "form-control" %>
        
          <%= f.label :lot, class: "label-class" %>
          <%= f.text_field :lot, class: "form-control" %>
          
          <%= f.label :expire, class: "label-class" %>
          <%= f.date_field :expire, class: "form-control" %>
          
          <%= f.label :product_amount, class: "label-class" %>
          <%= f.number_field :product_amount, class: "form-control" %>
        <% end %>
      </div>
      
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <table class="table table-condensed">
            <tr>
              <th>資材</th>
              <th>Lot</th>
              <th>在庫</th>
              <th>使用量</th>
            </tr>
            <tr>
              <td rowspan="2">化粧箱</td>
              <td>12345678</td>
              <td>200箱</td>
              <td>(入力）箱</td>
            </tr>
            <tr>
              <td>987654321</td>
              <td>250箱</td>
              <td>(入力)箱</td>
            </tr>
            <tr>
              <td rowspan="2">ロール</td>
              <td>12345678</td>
              <td>200m</td>
              <td>(入力）m</td>
            </tr>
            <tr>
              <td>987654321</td>
              <td>250m</td>
              <td>(入力)m</td>
            </tr>
            <tr>
              <td rowspan="2">段ボール</td>
              <td>12345678</td>
              <td>200c/s</td>
              <td>(入力）c/s</td>
            </tr>
            <tr>
              <td>987654321</td>
              <td>250c/s</td>
              <td>(入力)c/s</td>
            </tr>
            <tr>
              <td rowspan="2">造粒品</td>
              <td>12345678</td>
              <td>200kg</td>
              <td>(入力）kg</td>
            </tr>
            <tr>
              <td>987654321</td>
              <td>250kg</td>
              <td>(入力)kg</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goods/edit.js.erb
$("#edit").html("<%= escape_javascript(render'edit') %>");
$("#edit").modal("show");

app/views/goods/filling_report.js.erb
$("#filling-report").html("<%= escape_javascript(render'filling_report') %>");
$("#filling-report").modal("show");

app/views/goods/index.html.erb
<% provide(:title, "製品一覧") %>

<h1>製品一覧</h1>

<div class="col-md-6 col-md-offset-3">
  <table class="table table-condensed table-hover" id="table-goods">
    <thead>
      <tr>
        <th>発注元</th>
        <th>製品名</th>
        <th>入数</th>
        <th>在庫確認</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>
    
    <% @goods.each do |g| %>
      <tr>
        <td><%= g.client_name %></td>
        <td><%= g.goods_name %></td>
        <td><%= g.quantity %></td>
        <td>
          <%= link_to "在庫確認", stock_good_path(g), class: "btn btn-primary" %>
        </td>
        <td>
          <%= link_to "編集", edit_good_path(g), remote: true, class: "btn btn-success" %>
        </td>
        <td>
          <%= link_to "削除", g, method: :delete,
          data: { confirm: "削除してよろしいですか？" },
          class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<!-- モーダルウィンドウ表示 -->
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/goods/new.html.erb
<% provide(:ttile, "製品登録") %>
<% provide(:class_text, "good--new") %>
<% provide(:button_text, "登録") %>

<h1>製品登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @good, local: true) do |f| %>
      <%= render "shared/error_messages", model: f.object %>
      
      <%= f.label :client_name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :client_name, class: "form-control" %>
      
      <%= f.label :goods_name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :goods_name, class: "form-control" %>
      
      <%= f.label :quantity, class: "label-#{yield(:class_text)}" %>
      <%= f.number_field :quantity, class: "form-control new_quantity_field", step: 5 %>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>
  

app/views/goods/product_report.html.erb
<% provide(:title, "生産報告") %>

<h1>生産報告</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="product_reports">
    <thead>
      <tr>
        <th>生産品目</th>
        <th>充填</th>
        <th>造粒</th>
      </tr>
    </thead>
    
    <% @goods.each do |g| %>
      <tr>
        <td>
          <%= g.client_name %>  <%= g.goods_name %> <%= g.quantity %>
        </td>
        <td><%= link_to "生産報告", filling_report_good_path(g), remote: true, class: "btn btn-primary " %></td>
        <td><%= link_to "生産報告", '#', class: "btn btn-success " %></td>
      </tr>
    <% end %>
  </table>
</div>

<!-- モーダルウィンドウ表示 -->
<div id="filling-report" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/goods/stock.html.erb
<% provide(:title, "製品在庫") %>

<h1><%= @good.client_name %> <%= @good.goods_name %> <%= @good.quantity %>包</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-goods_stock" >
    <thead>
      <th>日付</th>
      <th>Lot</th>
      <th>賞味期限</th>
      <th>生産量</th>
      <th>出荷量</th>
      <th>在庫</th>
    </thead>
    
    <tr>
      <td>前月繰越分</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>c/s</td>
    </tr>
    
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>c/s</td>
      </tr>
  </table>
</div>