config/routes.rb
Rails.application.routes.draw do
  get 'goods/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :goods do
    member  do
      get 'stock'
      get 'filling_report'
      patch 'filling_report_func'
    end
  end
  
  get '/product_reports', to: 'goods#product_report'
  resources :items do
    member do
      get 'edit_material_info'
      patch 'update_material_info'
    end
    resources :products do
      member do
        get 'production_new'
        patch 'production_create'
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :good
  has_many :products, dependent: :destroy
  
  validates :note, length: { maximum: 30 }
  validates :material_name, presence: true
  validates :contact_order, presence: true
  validates :unit_price, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy, :edit_material_info, :update_material_info]
  before_action :logged_in_user, only: [:show, :edit, :update, :index, :destroy]
  
  def index
    @items = Item.paginate(page: params[:page])
    @items = @items.where('material_name LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end
  
  def show
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "登録しました"
      redirect_to items_path
    else
      render :new
    end 
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
    @item.destroy
    flash[:success] = "#{@item.material_name}のデータを削除しました。"
    redirect_to items_url
  end
  
  def edit_material_info
  end 
  
  def update_material_info
    if @item.update_attributes(item_params)
      flash[:success] = "原料情報を更新しました。"
      redirect_to items_path
    else
      @items = Item.paginate(page: params[:page])
      @items = @items.where('material_name LIKE ?', "%#{params[:search]}%") if params[:search].present?
      flash[:danger] = "入力エラーが#{@item.errors.count}件ありました。<br>" + @item.errors.full_messages.join("<br>")
      redirect_to action: :index
    end
  end
  
  private
    
    def item_params
      params.require(:item).permit(:material_name, :contact_order, :unit_price, :allergy)
    end
    
    def set_item
      @item = Item.find(params[:id])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
  
  def presence_or_absence_of_allergy(allergy)
    allergy ? "あり" : "なし"
  end
  
  def allergy_color(allergy)
    if allergy
      return "have_allergy"
    end
  end
end

app/views/items/_edit_material_info.html.erb
<% provide(:class_text, "item--edit") %>
<% provide(:button_text, "更新") %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">原料情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @item, url: update_material_info_item_path(@item), local: true) do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
            
            <%= f.label :material_name, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :material_name, class: "form-control" %>
            
            <%= f.label :contact_order, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :contact_order, class: "form-control" %>
            
            <%= f.label :unit_price, class: "label-#{yield(:class_text)}" %>
            <%= f.number_field :unit_price, class: "form-control" %>
            
            <p class="">アレルギー物質の有無</p>
            <div>
              <%= f.radio_button :allergy, :false, checked: true %>
              <%= f.label :allergy, "なし", { value: :false, style: "display: inline-block" } %>
              <%= f.radio_button :allergy, :true %>
              <%= f.label :allergy, "あり", { value: :true, style: "display: inline-block" } %>
            </div>
            
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>   
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_item_form.html.erb
<%= form_with(model: @item, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  
  <%= f.label :material_name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :material_name, class: "form-control" %>
  
  <%= f.label :contact_order, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :contact_order, class: "form-control" %>
  
  <%= f.label :unit_price, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :unit_price, class: "form-control" %>
  
  <p class="">アレルギー物質の有無</p>
  <div>
    <%= f.radio_button :allergy, :false, checked: true %>
    <%= f.label :allergy, "なし", { value: :false, style: "display: inline-block" } %>
    <%= f.radio_button :allergy, :true %>
    <%= f.label :allergy, "あり", { value: :true, style: "display: inline-block" } %>
  </div>
  
  <div class="center">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
    <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
      キャンセル
    </button>   
  </div>
  
<% end %>

app/views/items/edit.html.erb
<% provide(:title, "原料の編集") %>
<% provide(:class_text, "item--edit") %>
<% provide(:button_text, "更新") %>
<h1>原料情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'item_form' %>
  </div>
</div>

app/views/items/edit_material_info.js.erb
$("#edit-material-info").html("<%= escape_javascript(render'edit_material_info') %>");
$("#edit-material-info").modal("show");

app/views/items/index.html.erb
<% provide(:title, "造粒原料一覧") %>

<h1>造粒原料一覧</h1>
<div class="col-md-10 col-md-offset-1">
  <%= form_with(url: items_path, method: :get, local: true) do |f| %>
    <%= f.text_field :search %>
    <%= f.submit '検索', name: nil, class: "btn btn-sm btn-primary" %>
  <% end %>
</div>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-items">
    <thead>
      <tr> 
        <th>原料名</th>
        <th>発注先</th>
        <th>単価</th>
        <th>アレルギー</th>
        <th>編集</th>
        <th>入荷</th>
        <th>削除</th>
      </tr>
    </thead>
    
    <% @items.each do |item| %>
      <tr>
        <td><%= item.material_name %></td>
        <td><%= item.contact_order %></td>
        <td><%= item.unit_price %></td>
        <td class="<%= allergy_color(item.allergy) %>"><%= presence_or_absence_of_allergy(item.allergy) %></td>
        <% if current_user.admin? %>
        <td>
          <%= link_to "編集", edit_material_info_item_path(item), remote: true, class: "btn btn-success" %>
        </td>
        <td>
          <%= link_to "入荷", new_item_product_path(item), remote: true, class: "btn btn-primary" %>
        </td>
        <td>
          <%= link_to "削除", item, method: :delete,
          data: { confirm: "削除してよろしいですか？" },
          class: "btn btn-danger" %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<!-- モーダルウィンドウ表示 -->
<div id="edit-material-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/items/new.html.erb
<% provide(:title, "原料登録") %>
<% provide(:class_text, "item--new") %>
<% provide(:button_text, "登録") %>
<h1>原料登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'item_form' %>
  </div>
</div>